// SPDX-License-Identifier: GPL-3.0-only
//
// Regenerate the read/write FOOTPRINT catalog + the STACK_SCRATCH region for
// ram.js. The footprint is the set of RAM addresses the game READS or WRITES over
// broad coverage — the authoritative state the convergent gate compares
// (core/equivalence.js -> convergentEquivalence). Emits a ram.js-ready block on
// stdout; paste it over the generated section at the bottom of optimized/ram.js.
//
//   node games/dkong/tools/footprint.mjs > /tmp/footprint-block.js
//
// Method (portable to the next game): dynamically hook read8/write8 (most writes
// are register-indirect — VRAM/sprite fills via HL/IX — so a source grep misses
// them), run broad coverage, and record the union of touched addresses. Measure
// the stack extent from SP's low-water-mark so the dead stack scratch can be
// EXCLUDED from the compare. Curated names (from ram.js's numeric exports) are
// kept; everything else gets a SCRATCH_/SPRITE_/VRAM_/STACK_ placeholder to be
// promoted as it is understood. Coverage caveat: only as complete as the paths run.

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Machine } from "../machine.js";
import * as RAM from "../optimized/ram.js";

const ROM_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "rom");
const romPath = join(ROM_DIR, "maincpu.bin");
if (!existsSync(romPath)) {
  console.error("ROM not built — run `make -C games/dkong rom` first.");
  process.exit(2);
}
const ROM = new Uint8Array(readFileSync(romPath));

// address -> curated ram.js name (numeric exports in the RAM regions only)
const NAME = new Map();
for (const [k, v] of Object.entries(RAM)) {
  if (typeof v === "number" && v >= 0x6000 && v <= 0x77ff) NAME.set(v, k);
}

const inRegions = (a) =>
  (a >= 0x6000 && a <= 0x6bff) || (a >= 0x7000 && a <= 0x73ff) || (a >= 0x7400 && a <= 0x77ff);

const touched = new Map(); // addr -> { r, w }
let minSp = 0x10000, maxSp = 0;

function traceRun(tape, frames) {
  const m = new Machine(ROM, {});
  if (tape) m.inputTape = tape.map((t) => ({ ...t }));
  const rd = m.mem.read8.bind(m.mem);
  const wr = m.mem.write8.bind(m.mem);
  const sampleSp = () => {
    const sp = m.regs.sp; // ignore pre-init sp (0); the stack lives in high work RAM
    if (sp >= 0x6000 && sp <= 0x6c00) { if (sp < minSp) minSp = sp; if (sp > maxSp) maxSp = sp; }
  };
  m.mem.read8 = (a) => { if (inRegions(a)) { const e = touched.get(a) || { r: 0, w: 0 }; e.r = 1; touched.set(a, e); } sampleSp(); return rd(a); };
  m.mem.write8 = (a, v, b) => { if (inRegions(a)) { const e = touched.get(a) || { r: 0, w: 0 }; e.w = 1; touched.set(a, e); } sampleSp(); return wr(a, v, b); };
  m.runFrames(frames);
}

// Coverage: attract, then a credited game deep enough to reach barrel gameplay.
traceRun(null, 2500);
traceRun(
  [{ port: 0x7d00, bits: 0x80, frame: 10, dur: 6 }, { port: 0x7d00, bits: 0x04, frame: 30, dur: 6 }],
  3000,
);

const STACK_LO = minSp, STACK_HI = maxSp;
const hex = (a) => "0x" + a.toString(16).padStart(4, "0");
function placeholder(a) {
  if (a >= STACK_LO && a < STACK_HI) return "STACK_" + a.toString(16);
  if (a >= 0x7000 && a <= 0x73ff) return "SPRITE_" + a.toString(16);
  if (a >= 0x7400 && a <= 0x77ff) return "VRAM_" + a.toString(16);
  return "SCRATCH_" + a.toString(16);
}

const addrs = [...touched.keys()].sort((x, y) => x - y);
let named = 0, placeholders = 0;
const lines = addrs.map((a) => {
  const e = touched.get(a);
  const rw = (e.r ? "r" : "-") + (e.w ? "w" : "-");
  let name = NAME.get(a);
  if (name) named++; else { name = placeholder(a); placeholders++; }
  return `  ${hex(a)}: "${name}", // ${rw}`;
});

process.stdout.write(`// ─────────────────────────────────────────────────────────────────────────────
// COMPLETE READ/WRITE FOOTPRINT  (generated by tools/footprint.mjs, ${addrs.length} addresses)
// ─────────────────────────────────────────────────────────────────────────────
// Every RAM address the game READS or WRITES over broad coverage (attract 2500f +
// credited game 3000f). The authoritative set the convergent gate compares:
// PERSISTENT divergence at any of these (except STACK_SCRATCH) fails; transient
// reconverging divergence is tolerated; PIXELS are the hard ground truth.
// Curated names (${named}) come from the exports above; the rest (${placeholders}) are
// placeholders to be promoted as understood. Coverage: only as complete as paths run.
//
// STACK scratch (read+written but DEAD — excluded from the compare): [${hex(STACK_LO)}, ${hex(STACK_HI)}).

export const STACK_SCRATCH = { lo: ${hex(STACK_LO)}, hi: ${hex(STACK_HI)} };

export const FOOTPRINT = {
${lines.join("\n")}
};
`);
