# games/dkong — assemble your own ROM (copyrighted; never committed).
# See rom/README.md. Override the zip location with ROMZIP=/path/to/dkong.zip.

.PHONY: rom
rom:
	node ../../tools/build-rom.mjs dkong $(ROMZIP)
